steps:
  CURRENT_VALUES_DEBRIS-29:
    operation:
      config:
        deleteValue: D
        isOnlyCurrent: true
        lagSpec:
          items:
            - lagNumber: 60
              lagType: Minutes
        lagSpecification:
          items:
            - lagNumber: "60"
              lagType: Minutes
        nonDelete: true
        postSQL: ""
        preSQL: ""
        testsEnabled: true
        trackChanges: false
        whName: packages_wh
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: UTILS
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - columnReference:
              columnCounter: 819
              stepCounter: "29"
            config:
              keyColumn: true
            dataType: NUMBER(38,0)
            description: ""
            hashColumns: []
            hashDetails: null
            name: CC_CALL_CENTER_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 1043
                    stepCounter: "33"
                transform: ""
          - columnReference:
              columnCounter: 820
              stepCounter: "29"
            dataType: VARCHAR(16777216)
            description: ""
            hashColumns: []
            hashDetails: null
            name: CC_NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 1044
                    stepCounter: "33"
                transform: ""
          - columnReference:
              columnCounter: 821
              stepCounter: "29"
            dataType: VARCHAR(16777216)
            description: ""
            hashColumns: []
            hashDetails: null
            name: CC_CLASS
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 1045
                    stepCounter: "33"
                transform: ""
          - columnReference:
              columnCounter: 822
              stepCounter: "29"
            config:
              timeColumn: true
            dataType: TIMESTAMP
            description: ""
            hashColumns: []
            hashDetails: null
            name: CC_UPDATE_TS
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 1069
                    stepCounter: "33"
                transform: ""
          - columnReference:
              columnCounter: 823
              stepCounter: "29"
            config:
              dmlColumn: true
            dataType: VARCHAR(16777216)
            description: ""
            hashColumns: []
            hashDetails: null
            name: CC_DML_TYPE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 1070
                    stepCounter: "33"
                transform: ""
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - aliases:
              DT_CALL_CENTER: "33"
            customSQL:
              customSQL: ""
            dependencies:
              - locationName: UTILS
                nodeName: DT_CALL_CENTER
            join:
              joinCondition: FROM {{ ref('UTILS', 'DT_CALL_CENTER') }} "DT_CALL_CENTER"
            name: CURRENT_VALUES_DEBRIS
            noLinkRefs: []
      name: CURRENT_VALUES_DEBRIS
      overrideSQL: false
      schema: ""
      sqlType: "6"
      type: sql
    stepCounter: "29"
