steps:
  PROPAGATE_CURRENT_VALUES_DEBRIS-30:
    operation:
      config:
        deleteValue: D
        isOnlyCurrent: true
        lagSpec:
          items:
            - lagNumber: 60
              lagType: Minutes
        nonDelete: true
        postSQL: ""
        preSQL: ""
        testsEnabled: true
        trackChanges: false
        whName: packages
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: UTILS
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - columnReference:
              columnCounter: 887
              stepCounter: "30"
            config:
              keyColumn: true
            dataType: NUMBER(38,0)
            description: ""
            hashColumns: []
            hashDetails: null
            name: CC_CALL_CENTER_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 425
                    stepCounter: "19"
                transform: ""
          - columnReference:
              columnCounter: 888
              stepCounter: "30"
            dataType: VARCHAR(16777216)
            description: ""
            hashColumns: []
            hashDetails: null
            name: CC_NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 426
                    stepCounter: "19"
                transform: ""
          - columnReference:
              columnCounter: 889
              stepCounter: "30"
            dataType: VARCHAR(16777216)
            description: ""
            hashColumns: []
            hashDetails: null
            name: CC_CLASS
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 427
                    stepCounter: "19"
                transform: ""
          - columnReference:
              columnCounter: 890
              stepCounter: "30"
            config:
              timeColumn: true
            dataType: DATE
            description: ""
            hashColumns: []
            hashDetails: null
            name: CC_UPDATE_TS
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 451
                    stepCounter: "19"
                transform: ""
          - columnReference:
              columnCounter: 891
              stepCounter: "30"
            config:
              dmlColumn: true
            dataType: VARCHAR(16777216)
            description: ""
            hashColumns: []
            hashDetails: null
            name: CC_DML_TYPE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 452
                    stepCounter: "19"
                transform: ""
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - aliases:
              DT_CALL_CENTER: "33"
            customSQL:
              customSQL: ""
            dependencies:
              - locationName: UTILS
                nodeName: DT_CALL_CENTER
            join:
              joinCondition: FROM {{ ref('UTILS', 'DT_CALL_CENTER') }} "DT_CALL_CENTER"
            name: PROPAGATE_CURRENT_VALUES_DEBRIS
            noLinkRefs: []
      name: PROPAGATE_CURRENT_VALUES_DEBRIS
      overrideSQL: false
      schema: ""
      sqlType: "6"
      type: sql
    stepCounter: "30"
