steps:
  DEFAULT_VALUES-26:
    operation:
      config:
        changeTracking: false
        dmlDelete: D
        isCurVal: false
        lagSpecification:
          items:
            - lagNumber: 60
              lagType: Minutes
        postSQL: ""
        preSQL: ""
        propNonDelete: false
        testsEnabled: true
        whName: packages
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: UTILS
      materializationType: table
      metadata:
        appliedNodeTests: []
        columns:
          - columnReference:
              columnCounter: 645
              stepCounter: "26"
            config: {}
            dataType: NUMBER(38,0)
            description: ""
            hashColumns: []
            hashDetails: null
            name: CC_CALL_CENTER_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 425
                    stepCounter: "19"
                transform: ""
          - columnReference:
              columnCounter: 646
              stepCounter: "26"
            dataType: VARCHAR(16777216)
            description: ""
            hashColumns: []
            hashDetails: null
            name: CC_NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 426
                    stepCounter: "19"
                transform: ""
          - columnReference:
              columnCounter: 647
              stepCounter: "26"
            dataType: VARCHAR(16777216)
            description: ""
            hashColumns: []
            hashDetails: null
            name: CC_CLASS
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 427
                    stepCounter: "19"
                transform: ""
          - columnReference:
              columnCounter: 648
              stepCounter: "26"
            config: {}
            dataType: DATE
            description: ""
            hashColumns: []
            hashDetails: null
            name: CC_UPDATE_TS
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 451
                    stepCounter: "19"
                transform: ""
          - columnReference:
              columnCounter: 649
              stepCounter: "26"
            dataType: VARCHAR(16777216)
            description: ""
            hashColumns: []
            hashDetails: null
            name: CC_DML_TYPE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 452
                    stepCounter: "19"
                transform: ""
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SRC
                nodeName: STG_CALL_CENTER
            join:
              joinCondition: FROM {{ ref('SRC', 'STG_CALL_CENTER') }} "STG_CALL_CENTER"
            name: DEFAULT_VALUES
            noLinkRefs: []
      name: DEFAULT_VALUES
      overrideSQL: false
      schema: ""
      sqlType: "6"
      type: sql
    stepCounter: "26"
