steps:
  PROPAGATE_CURRENT_VALUES-24:
    operation:
      config:
        dmlDelete: D
        isCurVal: true
        lagSpec:
          items:
            - lagNumber: 60
              lagType: Minutes
        nonDelete: true
        postSQL: ""
        preSQL: ""
        testsEnabled: true
        trackChanges: true
        whName: packages
      database: ""
      dependencies: []
      deployEnabled: true
      description: ""
      isDataVault: false
      isMultisource: false
      locationID: ""
      locationName: UTILS
      materializationType: table
      metadata:
        appliedNodeTests:
          - continueOnFailure: true
            description: ""
            name: No Null IDs
            runOrder: After
            templateString: |-
              select
                  cc_call_center_id id,
                  cc_name cn
              from
                  {{this}}
              where
                  cn is null;
          - continueOnFailure: true
            description: ""
            name: Only current values
            runOrder: After
            templateString: |-
              select
                  cc_call_center_id id,
                  is_current ic,
                  count(*) cnt
              from
                  {{this}}
              group by
                  id,
                  ic
              having
                  cnt > 1;
        columns:
          - columnReference:
              columnCounter: 544
              stepCounter: "24"
            config:
              keyColumn: true
            dataType: NUMBER(38,0)
            description: ""
            hashColumns: []
            hashDetails: null
            name: CC_CALL_CENTER_ID
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 425
                    stepCounter: "19"
                transform: ""
          - columnReference:
              columnCounter: 545
              stepCounter: "24"
            dataType: VARCHAR(16777216)
            description: ""
            hashColumns: []
            hashDetails: null
            name: CC_NAME
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 426
                    stepCounter: "19"
                transform: ""
          - columnReference:
              columnCounter: 546
              stepCounter: "24"
            dataType: VARCHAR(16777216)
            description: ""
            hashColumns: []
            hashDetails: null
            name: CC_CLASS
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 427
                    stepCounter: "19"
                transform: ""
          - columnReference:
              columnCounter: 547
              stepCounter: "24"
            config:
              timeColumn: true
            dataType: DATE
            description: ""
            hashColumns: []
            hashDetails: null
            name: CC_UPDATE_TS
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 451
                    stepCounter: "19"
                transform: ""
          - columnReference:
              columnCounter: 548
              stepCounter: "24"
            config:
              colDML: true
            dataType: VARCHAR(16777216)
            description: ""
            hashColumns: []
            hashDetails: null
            name: CC_DML_TYPE
            nullable: true
            sourceColumnReferences:
              - columnReferences:
                  - columnCounter: 452
                    stepCounter: "19"
                transform: ""
        cteString: ""
        enabledColumnTestIDs: []
        sourceMapping:
          - customSQL:
              customSQL: ""
            dependencies:
              - locationName: SRC
                nodeName: STG_CALL_CENTER
            join:
              joinCondition: FROM {{ ref('SRC', 'STG_CALL_CENTER') }} "STG_CALL_CENTER"
            name: PROPAGATE_CURRENT_VALUES
            noLinkRefs: []
      name: PROPAGATE_CURRENT_VALUES
      overrideSQL: false
      schema: ""
      sqlType: "6"
      type: sql
    stepCounter: "24"
